services:
  mc:
    extends:
      file: ../../../templates/minecraft.compose.yml
      service: mc-base
    environment:
      MOTD: "\u00a7c\u00a7l@ abyssal.cow.pet @\u00a7r\n\u00a73MEET MILFS\u00a7r | \u00a76PET ANDREW\u00a7r | \u00a7dPUNCH DAVID"
      ICON: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Spot_the_cow.png"
      TYPE: "CUSTOM"
      CUSTOM_SERVER: "/data/server.jar"
      MEMORY: "13G"
    labels:
      mc-router.port: 25569

networks:
  minecraft:
    external: true