services:
  minepanel:
    image: ketbom/minepanel:latest
    volumes:
      - ${BASE_DIR}/servers:/app/servers
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    env_file: .env
    labels:
      - "traefik.enable=true"

      # Frontend (Next.js) - minepanel.cow.pet
      - "traefik.http.routers.minepanel.entrypoints=web"
      - "traefik.http.routers.minepanel.rule=Host(`minepanel.cow.pet`)"
      - "traefik.http.routers.minepanel-secure.entrypoints=websecure"
      - "traefik.http.routers.minepanel-secure.rule=Host(`minepanel.cow.pet`)"
      - "traefik.http.services.minepanel.loadbalancer.server.port=3000"
      - "traefik.http.routers.minepanel.service=minepanel"
      - "traefik.http.routers.minepanel-secure.service=minepanel"

      # Backend (Nest) - minepanel.cow.pet/api
      - "traefik.http.middlewares.minepanel-strip-api.stripPrefix.prefixes=/api"
      - "traefik.http.routers.minepanel-api.entrypoints=web"
      - "traefik.http.routers.minepanel-api.rule=Host(`minepanel.cow.pet`) && PathPrefix(`/api`)"
      - "traefik.http.routers.minepanel-api.middlewares=minepanel-strip-api"
      - "traefik.http.routers.minepanel-api-secure.entrypoints=websecure"
      - "traefik.http.routers.minepanel-api-secure.rule=Host(`minepanel.cow.pet`) && PathPrefix(`/api`)"
      - "traefik.http.routers.minepanel-api-secure.middlewares=minepanel-strip-api"
      - "traefik.http.services.minepanel-api.loadbalancer.server.port=8091"
      - "traefik.http.routers.minepanel-api.service=minepanel-api"
      - "traefik.http.routers.minepanel-api-secure.service=minepanel-api"
    restart: always
    networks:
      - traefik

networks:
  traefik:
    external: true